config:
  security:
    jwt-secret: secret
    access-token-duration-minutes: 10
    refresh-token-duration-minutes: 30
  postgres:
    url: localhost:5432
    db-name: shop_app_db
    username: postgres
    password: postgres
  cron:
    currency-rate: 0 15 17 * * ?

server:
  port: 20000

spring:
  datasource:
    url: jdbc:postgresql://${config.postgres.url}/${config.postgres.db-name}
    username: ${config.postgres.username}
    password: ${config.postgres.password}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

nbp:
  currency-rate:
    download-url: http://api.nbp.pl/api/exchangerates/tables/A/
    timeout-ms: 4000